# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "🚀 CI build (unsigned, no IPA export)"
  lane :build_ci do
    project_path = File.expand_path("../SpeechToText.xcodeproj", __dir__)

    sh("xcodebuild -scheme SpeechToText \
      -project #{project_path} \
      -configuration Debug \
      -sdk iphonesimulator \
      build")

    UI.success("🎉 Build completed successfully! (No signing, no IPA)")
  end
end
